# Generated by Django 5.1 on 2024-08-14 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0003_remove_team_players'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.competition')),
                ('players', models.ManyToManyField(to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
