# Generated by Django 5.1 on 2024-08-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_competitionsquad'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtype',
            name='activePlayersPerTeam',
            field=models.IntegerField(default=11),
        ),
    ]
