# Generated by Django 5.1 on 2024-08-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
    ]
