# Generated by Django 5.1 on 2024-08-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fav_sport',
            new_name='favSport',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='has_accepted_nl',
            new_name='hasAcceptedNL',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='has_accepted_pp',
            new_name='hasAcceptedPP',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='has_accepted_tc',
            new_name='hasAcceptedTC',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_account',
            new_name='userAccount',
        ),
    ]
