# Generated by Django 5.1 on 2024-08-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='isExpired',
            new_name='isActive',
        ),
    ]
