# Generated by Django 5.1 on 2024-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_isexpired_usersubscription_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
