# Generated by Django 5.1 on 2024-08-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0001_initial'),
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dayOrNight', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('DayNight', 'DayNight')], max_length=15)),
                ('optTo', models.CharField(blank=True, choices=[('Batting', 'Batting'), ('Fielding', 'Fielding')], max_length=15, null=True)),
                ('fisrtInningsCondition', models.CharField(blank=True, choices=[('Day', 'Day'), ('Under Lights', 'Under Lights')], max_length=15, null=True)),
                ('secondInningsCondition', models.CharField(blank=True, choices=[('Day', 'Day'), ('Under Lights', 'Under Lights')], max_length=25, null=True)),
                ('captain1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_captainA', to='player.player')),
                ('captain2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_captainB', to='player.player')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.competition')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('knockout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.knockout')),
                ('matchType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.matchtype')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_teamA', to='team.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_teamB', to='team.team')),
                ('teamBattingFirst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_teamBattingFirst', to='team.team')),
                ('teamBattingSecond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_teamBattingSecond', to='team.team')),
                ('tossWonBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_toss_won_by', to='team.team')),
                ('wicketKeeper1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_wicket_keeperA', to='player.player')),
                ('wicketKeeper2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_wicket_keeperB', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayingEleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField(blank=True, null=True)),
                ('battingOrder', models.IntegerField()),
                ('substitute', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.stadium'),
        ),
    ]
