# Generated by Django 5.1 on 2024-08-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='umpire1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_umpire1', to='player.umpire'),
        ),
        migrations.AddField(
            model_name='match',
            name='umpire2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_umpire2', to='player.umpire'),
        ),
        migrations.AddField(
            model_name='match',
            name='umpire3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_umpire3', to='player.umpire'),
        ),
    ]
