# Generated by Django 5.1 on 2024-08-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_umpire1_match_umpire2_match_umpire3'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.nationality'),
        ),
    ]
